---
- name: install golang
  shell: curl https://go.googlecode.com/files/go1.2.linux-amd64.tar.gz | tar -zxC /usr/local
         creates=/usr/local/go

- name: configure path
  copy: src=golang.sh
        dest=/etc/profile.d/golang.sh
        owner=root
        group=root
        mode=0644
